// Date: 22/04/2013 20:49:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package chicktherm.fantasypack.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelFairy extends ModelBase
{
  //fields
    ModelRenderer rightwing;
    ModelRenderer Head;
    ModelRenderer Rightarm;
    ModelRenderer Rightleg;
    ModelRenderer Body;
    ModelRenderer leftwing;
    ModelRenderer Leftleg;
    ModelRenderer Leftarm;
  
  public ModelFairy()
  {
    textureWidth = 20;
    textureHeight = 18;
    
      rightwing = new ModelRenderer(this, 0, 13);
      rightwing.addBox(-3F, 0F, 0F, 3, 2, 1);
      rightwing.setRotationPoint(-1F, 16F, 1F);
      rightwing.setTextureSize(20, 18);
      rightwing.mirror = true;
      setRotation(rightwing, 0F, 1.570796F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 4, 4, 4);
      Head.setRotationPoint(-2F, 12F, 2F);
      Head.setTextureSize(20, 18);
      Head.mirror = true;
      setRotation(Head, 0F, 1.570796F, 0F);
      Rightarm = new ModelRenderer(this, 4, 8);
      Rightarm.addBox(0F, 0F, 0F, 1, 4, 1);
      Rightarm.setRotationPoint(-2F, 16F, 0F);
      Rightarm.setTextureSize(20, 18);
      Rightarm.mirror = true;
      setRotation(Rightarm, 0F, 0F, 0F);
      Rightleg = new ModelRenderer(this, 0, 8);
      Rightleg.addBox(-1F, 0F, 0F, 1, 4, 1);
      Rightleg.setRotationPoint(0F, 20F, 0F);
      Rightleg.setTextureSize(20, 18);
      Rightleg.mirror = true;
      setRotation(Rightleg, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 15, 11);
      Body.addBox(0F, 0F, 0F, 1, 4, 2);
      Body.setRotationPoint(-1F, 16F, 1F);
      Body.setTextureSize(20, 18);
      Body.mirror = true;
      setRotation(Body, 0F, 1.570796F, 0F);
      leftwing = new ModelRenderer(this, 8, 8);
      leftwing.addBox(-3F, 0F, 0F, 3, 2, 1);
      leftwing.setRotationPoint(0F, 16F, 1F);
      leftwing.setTextureSize(20, 18);
      leftwing.mirror = true;
      setRotation(leftwing, 0F, 1.570796F, 0F);
      Leftleg = new ModelRenderer(this, 0, 8);
      Leftleg.addBox(0F, 0F, 0F, 1, 4, 1);
      Leftleg.setRotationPoint(0F, 20F, 0F);
      Leftleg.setTextureSize(20, 18);
      Leftleg.mirror = true;
      setRotation(Leftleg, 0F, 0F, 0F);
      Leftarm = new ModelRenderer(this, 4, 8);
      Leftarm.addBox(0F, 0F, 0F, 1, 4, 1);
      Leftarm.setRotationPoint(1F, 16F, 0F);
      Leftarm.setTextureSize(20, 18);
      Leftarm.mirror = true;
      setRotation(Leftarm, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    rightwing.render(f5);
    Head.render(f5);
    Rightarm.render(f5);
    Rightleg.render(f5);
    Body.render(f5);
    leftwing.render(f5);
    Leftleg.render(f5);
    Leftarm.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
   
	  this.Rightarm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 2.0F * f1 * 0.5F;
      this.Leftarm.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
      this.Rightarm.rotateAngleZ = 0.0F;
      this.Leftarm.rotateAngleZ = 0.0F;
      this.Rightleg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.Leftleg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
      this.Rightleg.rotateAngleY = 0.0F;
      this.Leftleg.rotateAngleY = 0.0F;

      
    
  }
}

